source = palette.conf

$check = [ ! -e /tmp/inhibit ]

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({ action = 'on' })" ; $bright-res
}

# region 6 min

listener {
    timeout = 356
    on-timeout = hyprctl notify -1 4242 "##$pink" "Are you here?"
    condition_cmd = $check
}

listener {
    timeout = 360
    on-timeout = loginctl lock-session
    condition_cmd = $check
}

# endregion
# region 12 min

listener {
    timeout = 716
    on-timeout = hyprctl notify -1 4242 "##$pink" "I'm falling asleep"
    condition_cmd = $check
}

listener {
    timeout = 720
    on-timeout = $bright-off
    on-resume = $bright-res
    condition_cmd = $check
}

# endregion
# region 18 min

listener {
    timeout = 1076
    on-timeout = hyprctl notify -1 4242 "##$pink" "Sweet dreams"
    condition_cmd = $check
}

listener {
    timeout = 1080
    on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = 'off' })"
    condition_cmd = $check
}

# endregion
# region 24 min

listener {
    timeout = 1440
    condition_cmd = $check

    on-timeout = systemctl suspend
}

# endregion
